// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260325053456_InitialCreation")]
partial class InitialCreation
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("app")
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Domain.Jobs.Job", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("Jobs", "scheduling");
            });

        modelBuilder.Entity("Domain.Jobs.JobSchedule", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CronExpression")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit");

                b.Property<Guid>("JobId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<string>("TimeZoneId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("JobId", "IsEnabled");

                b.ToTable("JobSchedules", "scheduling");
            });

        modelBuilder.Entity("Domain.Jobs.JobStep", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("bit");

                b.Property<Guid>("JobId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("OnFailure")
                    .HasColumnType("int");

                b.Property<string>("Parameters")
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<int>("StepOrder")
                    .HasColumnType("int");

                b.Property<string>("StepType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("JobId", "StepOrder");

                b.ToTable("JobSteps", "scheduling");
            });

        modelBuilder.Entity("Domain.Todos.TodoItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset?>("CompletedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("DueDate")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsCompleted")
                    .HasColumnType("bit");

                b.PrimitiveCollection<string>("Labels")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Priority")
                    .HasColumnType("int");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("TodoItems", "app");
            });

        modelBuilder.Entity("Domain.Users.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("RowVersion")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("rowversion");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UpdatedBy")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users", "app");
            });

        modelBuilder.Entity("Infrastructure.Outbox.OutboxMessage", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Error")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsRelayed")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(false);

                b.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTime>("OccurredOnUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("ProcessingStartedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("QueueType")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasDefaultValue("default");

                b.Property<DateTime?>("RelayedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("TraceParent")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.HasKey("Id");

                b.HasIndex("IsRelayed", "ProcessingStartedAt");

                b.ToTable("OutboxMessages", "outbox");
            });

        modelBuilder.Entity("Domain.Jobs.JobSchedule", b =>
            {
                b.HasOne("Domain.Jobs.Job", null)
                    .WithMany("Schedules")
                    .HasForeignKey("JobId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Domain.Jobs.JobStep", b =>
            {
                b.HasOne("Domain.Jobs.Job", null)
                    .WithMany("Steps")
                    .HasForeignKey("JobId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Domain.Todos.TodoItem", b =>
            {
                b.HasOne("Domain.Users.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Domain.Jobs.Job", b =>
            {
                b.Navigation("Schedules");

                b.Navigation("Steps");
            });
#pragma warning restore 612, 618
    }
}
